feat: add top nav bar + add to home page (2nd)
treerspeaking/smart-printing-service pull request #4
Opened 2023-10-28 16:20 UTC by strayByte2022

Add top navbar

For home page: add new button + calendar

Add new route for YeuCauIn

2023-10-28 16:20 UTC, strayByte2022 commented
Duyệt nhanh cmn lên Tùng :))))

2023-10-29 04:01 UTC, strayByte2022 commented
Xem code đi troi oi 
Đã 48 tiếng r đó

2023-10-30 16:04 UTC, treerspeaking commented on src/App.jsx
> +            <Route path="/YeuCauIn" element={<PrintRequestPage></PrintRequestPage>}></Route>
Chỉnh sửa lại cái này giống format mấy cái trc đi

2023-10-30 16:43 UTC, treerspeaking requested changes

2023-10-30 16:43 UTC, treerspeaking commented on src/pages/Home/index.jsx
làm cả cái trang này 1 page thôi không có thanh kéo

chỉnh cái khoảng cách giữa cái nút và trang chủ nhỏ lại
chỉnh cái calendar nhỏ lại
chỉnh cái nút và cái calendar có khoảng cách đến cái table lịch sử như nhau

![image](https://github.com/treerspeaking/smart-printing-service/assets/93274119/38e75b99-a8c0-490b-a770-840e15fd4140)

2023-10-30 16:43 UTC, treerspeaking commented on src/pages/Home/DateTime.tsx
make the calendar smaller

2023-10-30 16:43 UTC, treerspeaking commented on src/pages/History/index.jsx
Làm tất cả cùng 1 kiểu chữ h2 đi

2023-10-30 16:43 UTC, treerspeaking commented on README.md
Chỉnh lại cái mấy cái readme này

2023-10-30 16:43 UTC, treerspeaking commented on src/pages/Home/PrintReqeust.tsx
> +    <Button variant='contained' sx={{width:161, height:57, borderRadius:100}} href='/YeuCauIn'>Đặt in mới</Button>
wrap cái này trong cái <Link> của react router

2023-10-30 16:43 UTC, treerspeaking commented on src/pages/Home/PrintReqeust.tsx
đặt tên file sai

2023-10-30 17:00 UTC, strayByte2022 commented on src/pages/Home/PrintReqeust.tsx
New name?

2023-10-30 17:01 UTC, strayByte2022 commented on src/pages/Home/PrintReqeust.tsx
> +    <Button variant='contained' sx={{width:161, height:57, borderRadius:100}} href='/YeuCauIn'>Đặt in mới</Button>
common practice for maintainance man:)

2023-10-30 17:02 UTC, strayByte2022 commented on src/pages/History/index.jsx
Chỉ có 1 cái heading thôi mà:D

2023-10-30 17:03 UTC, strayByte2022 commented on src/pages/Home/index.jsx
cái đó là cái tỉ lệ trong figma đó:)

2023-10-31 12:23 UTC, strayByte2022 commented on src/pages/Home/index.jsx
- Đã chỉnh calendar nhỏ hơn 20% so với lần trước
- Đã thu nhỏ khoảng cách giữa nút đặt in và dòng trang chủ: **260px => 200px**
- khoảng cách như nhau => **DONE**

2023-10-31 12:32 UTC, strayByte2022 commented on README.md
- Không nên để thẳng vào trong react router -> code rất rối, và khó maintain
- Tên file: **PrintRequest => PrintRequestButton**

2023-10-31 14:03 UTC, treerspeaking requested changes

2023-10-31 14:03 UTC, treerspeaking commented on src/pages/Home/PrintReqeust.tsx
PrintRequest

2023-10-31 14:03 UTC, treerspeaking commented on README.md
> -This is a project for Software Engineering Course, Semester 231.
cái này merge cái read.me sẽ thành

This is a project for Software Engineering Course, Semester 231.
This is Vuong Hong Linh's branch.

Remind: this works in github flow. 

đó Lĩnh

2023-10-31 15:30 UTC, strayByte2022 commented on README.md
> -This is a project for Software Engineering Course, Semester 231.
Fix rồi:D Nhầm tí

2023-11-01 06:01 UTC, treerspeaking approved these changes

2023-11-01 06:01 UTC, merged