Add Firebase Authentication
treerspeaking/smart-printing-service pull request #7
Opened 2023-11-11 14:11 UTC by ShunPeng1

2023-11-11 15:02 UTC, treerspeaking requested changes

2023-11-11 15:02 UTC, treerspeaking commented on src/pages/Login/Auth.jsx
> +
Create this with a React context watch this video from 8:36 to 20:20 
if you are wondering why we use context it is because we need other component to also have an idea of the email and password plus we could achieve code separation.
https://www.youtube.com/watch?v=PKwu15ldZ7k&t=516s

2023-11-11 15:02 UTC, treerspeaking commented on src/pages/Login/Auth.jsx
> +  	return (
uses Lĩnh login's page

2023-11-12 05:39 UTC, strayByte2022 commented on hello.txt
wtf on this man:))

2023-11-12 05:49 UTC, strayByte2022 commented on src/pages/Login/Auth.jsx
> +			console.log(error);
ah, this should add the notifications for wrong auth. 


`
<Alert severity="error">{error}</Alert>
`

2023-11-12 05:51 UTC, strayByte2022 reviewed
:)

2023-11-12 05:54 UTC, strayByte2022 commented on src/App.jsx
>            <Route path="/smart-printing-service" element={<Root/>}>
hmm why this is deleted man

2023-11-12 05:54 UTC, strayByte2022 commented on src/App.jsx
>            <Route path="/smart-printing-service" element={<Root/>}>
👇🏻

2023-11-12 15:10 UTC, treerspeaking approved these changes

2023-11-12 15:10 UTC, merged